## Pytorch

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("Yes available")
    print(f"GPU Name : {torch.cuda.get_device_name(0)}")
else:
    print("helll NOOOO")

Yes available
GPU Name : Tesla T4


## creating a Tensor
- also this is kinda similar with the numpy

In [ ]:
# using empty 
torch.empty(2,3) # so it is basically making a 2d tensor matrix; also it doesnt assign the value it is actually doesnt assign the value so it is actually assigning the already valued

tensor([[3.3350e+33, 4.4207e-41, 3.3350e+33],
        [4.4207e-41, 2.8164e-21, 0.0000e+00]])

In [ ]:
type(torch.empty(2,3)) # by using this we can actually claim that we have created a thing which is a tensor so yea 

torch.Tensor

In [ ]:
# Using the Zeros
torch.zeros(2,3) # so it is as like numpy zeros so all tensors are assigned zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Using Ones
torch.ones(2,3) # same as zero

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Using Rand -> rand means random 
torch.rand(2,3) # so it basically creates the values between zero to ones

tensor([[0.9982, 0.8198, 0.0918],
        [0.8959, 0.6869, 0.3726]])

In [ ]:
# use the seed
torch.rand(2,3)

tensor([[0.1310, 0.9422, 0.9374],
        [0.8398, 0.8848, 0.2590]])

In [ ]:
# manual seed -> so suppose if we want to reproduce the same value of the rand val sow we can use these. 
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# manual seed 
torch.manual_seed(100)
torch.rand(2,3) # So by using this if a value of rand provides me a vlaue and i wanwt that my fd should see the same value so yea we could use seeed that time 

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# Using Tensor 
torch.Tensor([[1,2,4],[1,2,3]]) # by using this it will make tensor of my providing values so yea 

tensor([[1., 2., 4.],
        [1., 2., 3.]])

In [ ]:
# other ways
# arange
print("Arrange using : ", torch.arange(0,10)) # range it is and in the last we can provide the step (0,10,2)

# using linspace
print("Using LinSpace : ", torch.linspace(0,10,10))

# using the eye
print("Using eye : ", torch.eye(5)) # eye for identity matrix 

# using the full 
print("Using full : ", torch.full((3,3),5)) # it means we need 3x3 matrix and it should  be full with 5 so yea


Arrange using :  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using LinSpace :  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye :  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[3,4,5]])
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [ ]:
x.shape # by using this we can cal shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) # it means like it is same shape as the previous x so yea

tensor([[   146930,         0,         0],
        [       33, 566619456, 601828752]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# torch.tensor(x, dtype=torch.float32)
# x.to(torch.float32)
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Tensor Data Type

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assigning the data type
torch.tensor([1.3,2.9,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# assigning the data type
torch.tensor([1.3,2.9,3.0], dtype=torch.float32)

tensor([1.3000, 2.9000, 3.0000])

In [ ]:
# using to 
z = x.to(torch.float32)
torch.rand_like(z)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

### Mathematical Operations

In [ ]:
# 1. scalar operation
y = torch.rand(2,2)
y

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [ ]:
# addi
y + 2
# sub
y- 2
# multi 
y *2
# div
y /2
# mod
y % 2
# int division
(y*100)//3
# power 
y**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [ ]:
a+b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [ ]:
a-b

tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])

In [ ]:
a*b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [ ]:
a/b

tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])

In [ ]:
a%b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [ ]:
a**b

tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])

In [ ]:
(a*100)//b

tensor([[229., 139.,  84.],
        [383.,  94., 115.]])

In [ ]:
c = torch.tensor([1,-3,2,-4])
c

tensor([ 1, -3,  2, -4])

In [ ]:
# abs
torch.absolute(c)

tensor([1, 3, 2, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  3, -2,  4])

In [ ]:
# round -> rounds the elements of an input tensor to the nearest integer
d = torch.tensor([1.9,7.3,3.4,3.2])
torch.round(d)

tensor([2., 7., 3., 3.])

In [ ]:
# ceil -> it goes to the upper closer number
torch.ceil(d)

tensor([2., 8., 4., 4.])

In [ ]:
# floor -> it same as ceil bt it goes to the down 
torch.floor(d)

tensor([1., 7., 3., 3.])

In [ ]:
# clamp
print(d)
torch.clamp(d, min=1, max=2)

tensor([1.9000, 7.3000, 3.4000, 3.2000])


tensor([1.9000, 2.0000, 2.0000, 2.0000])

### reduction Operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [ ]:
# sum
torch.sum(e)

tensor(28.)

In [ ]:
# sum along the colums
torch.sum(e, dim=0)

tensor([14., 11.,  3.])

In [ ]:
# sum along the rows
torch.sum(e, dim=1)

tensor([15., 13.])

In [ ]:
# mean
torch.mean(e)

tensor(4.6667)

In [ ]:
# mean along the col
torch.mean(e, dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [ ]:
# mean along the rows
torch.mean(e, dim=1)

tensor([5.0000, 4.3333])

In [ ]:
# median
torch.median(d)

tensor(3.2000)

In [ ]:
# max and min
print(torch.max(d))
print(torch.min(d))

tensor(7.3000)
tensor(1.9000)


In [ ]:
# product
torch.prod(d)

tensor(150.9056)

In [ ]:
# standard deviation
torch.std(d)

tensor(2.3302)

In [ ]:
# variance
torch.var(d)

tensor(5.4300)

In [ ]:
# argmax
torch.argmax(d)

tensor(1)

In [ ]:
# argmin
torch.argmin(d)

tensor(0)

### matrix multiplication

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g= torch.randint(size=(3,2),low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [ ]:
torch.matmul(f,g)

tensor([[116, 153],
        [166, 225]])

In [ ]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,5])

# dot 
torch.dot(vec1,vec2)

tensor(13)

In [ ]:
# transpose
print(f)
torch.transpose(f, 0,1) # 0 adn 1 is the dimension so i want to transpose 0 with 1 uea thats all

tensor([[5, 7, 5],
        [9, 9, 7]])


tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [ ]:
# deerminent
torch.det(h)

tensor(-315.)

In [ ]:
# inverse 
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

In [ ]:
i = torch.randint(size=(2,3),low=0, high=10)
j = torch.randint(size=(2,3),low=0, high=10)
print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [ ]:
# grater than
i>j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [ ]:
# less than
i<j

tensor([[False,  True,  True],
        [False, False, False]])

In [ ]:
# equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# grater than equal to
i>=j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [ ]:
# less than equal to
i<=j

tensor([[False,  True,  True],
        [False, False, False]])

In [ ]:
# special functions
k = torch.randint(size=(2,3), low=0, high=10)
k

tensor([[0, 8, 4],
        [7, 2, 3]])

In [ ]:
# log 
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [ ]:
#exponents
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [ ]:
# softmax
torch.softmax(k, dim=0, dtype=torch.float32)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [ ]:
# ReLU
torch.relu(k)

tensor([[0, 8, 4],
        [7, 2, 3]])

In [ ]:
# Implace Operations
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [ ]:
m.add_(n) # it means that we are doing m+n and that sum storing at m again so it not gonna eat much memory so yea

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [ ]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [ ]:
torch.relu(m)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [ ]:
m.relu_()

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

### Copying a tensor


In [ ]:
p = torch.rand(2,3)
p

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [ ]:
p.copy_(m)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [ ]:
id(p)

135490129558848

In [ ]:
id(m)

135490129557728

In [ ]:
print(p)
b = p.clone() # by using this we get completly new with new memory location so yea also if we assign with a=b it doesnt gonna effect that
b

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])


tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

## Tensor Operations on GPU


In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# Creating a new tensor on gpu
torch.rand((2,3),device=device)

tensor([[0.8344, 0.7001, 0.5361],
        [0.8883, 0.0220, 0.7938]], device='cuda:0')

In [ ]:
# moving an existing tensor on gpu
print(a) # this is based on cpu
b = a.to(device) # this is moved to gpu 
b

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]], device='cuda:0')

In [ ]:
b + 5 # now we are performing this on gpu

tensor([[5.5557, 5.9770, 5.4440],
        [5.9478, 5.7445, 5.4892]], device='cuda:0')

In [ ]:
import torch
import time

size = 10000

matrixOnCpu1 = torch.randn(size, size)
matrixOnCpu2 = torch.randn(size, size)

startTime = time.time()
resultCpu = torch.matmul(matrixOnCpu1, matrixOnCpu2)
cpuTime = time.time() - startTime

print(f"Time on cpu : {cpuTime:.2f} seconds ")

matrixOnGpu1 = matrixOnCpu1.to('cuda')
matrixOnGpu2 = matrixOnCpu2.to('cuda')

# time measure on gopu
startTime = time.time()
resultGpu = torch.matmul(matrixOnGpu1, matrixOnGpu2)
torch.cuda.synchronize() # by using this we are ensuring that all operations on gpu done perfectly 
gpuTime = time.time() - startTime

print(f"Time on Gpu : {gpuTime:.4f} seconds\n")

# comparing the results 
print("SpeedUp (cpu time/ gpu time) : ", cpuTime/gpuTime)


Time on cpu : 16.33 seconds 
Time on Gpu : 0.7560 seconds

SpeedUp (cpu time/ gpu time) :  21.59964428298424


### Reshaping Tensors

In [ ]:
a = torch.ones(4,4)

In [ ]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten - it converts the whole things into the 1d so yea
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.8034, 0.5529, 0.8144, 0.9209],
         [0.7333, 0.7789, 0.7098, 0.5061],
         [0.3124, 0.4449, 0.1651, 0.3282]],

        [[0.0891, 0.1407, 0.2274, 0.7484],
         [0.4540, 0.5532, 0.7203, 0.9523],
         [0.8353, 0.6273, 0.0440, 0.0258]]])

In [ ]:
# permute 
b.permute(2,0,1) # so it basically convers the size to [4,2,3]

tensor([[[0.8034, 0.7333, 0.3124],
         [0.0891, 0.4540, 0.8353]],

        [[0.5529, 0.7789, 0.4449],
         [0.1407, 0.5532, 0.6273]],

        [[0.8144, 0.7098, 0.1651],
         [0.2274, 0.7203, 0.0440]],

        [[0.9209, 0.5061, 0.3282],
         [0.7484, 0.9523, 0.0258]]])

In [ ]:
b.permute(2,0,1).size()

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze - basically it does a thing which is its add new dimention in a positon
c = torch.rand(226,226,3) # basiacally it is the size of the image 
c.unsqueeze(1).shape


torch.Size([226, 1, 226, 3])

In [ ]:
# squeeze 
d = torch.rand(1,20)
d.squeeze(0).shape # so it basiacally removes the 1 then just keeped the 20 

torch.Size([20])

In [ ]:
import numpy as np

In [ ]:
a = torch.Tensor([1,2,3,4])
a

tensor([1., 2., 3., 4.])

In [ ]:
type(a)

torch.Tensor

In [ ]:
b = a.numpy()
b

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = torch.from_numpy(b)
c

tensor([1., 2., 3., 4.])

In [ ]:
type(c)

torch.Tensor