## Pytorch

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
    print("Yes available")
    print(f"GPU Name : {torch.cuda.get_device_name(0)}")
else:
    print("helll NOOOO")

Yes available
GPU Name : Tesla T4


## creating a Tensor
- also this is kinda similar with the numpy

In [3]:
# using empty 
torch.empty(2,3) # so it is basically making a 2d tensor matrix; also it doesnt assign the value it is actually doesnt assign the value so it is actually assigning the already valued

tensor([[4.5368e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [4]:
type(torch.empty(2,3)) # by using this we can actually claim that we have created a thing which is a tensor so yea 

torch.Tensor

In [5]:
# Using the Zeros
torch.zeros(2,3) # so it is as like numpy zeros so all tensors are assigned zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Using Ones
torch.ones(2,3) # same as zero

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# Using Rand -> rand means random 
torch.rand(2,3) # so it basically creates the values between zero to ones

tensor([[0.8019, 0.5170, 0.6443],
        [0.8404, 0.9106, 0.5811]])

In [8]:
# use the seed
torch.rand(2,3)

tensor([[0.9731, 0.6586, 0.4584],
        [0.6222, 0.6309, 0.4399]])

In [9]:
# manual seed -> so suppose if we want to reproduce the same value of the rand val sow we can use these. 
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# manual seed 
torch.manual_seed(100)
torch.rand(2,3) # So by using this if a value of rand provides me a vlaue and i wanwt that my fd should see the same value so yea we could use seeed that time 

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
# Using Tensor 
torch.Tensor([[1,2,4],[1,2,3]]) # by using this it will make tensor of my providing values so yea 

tensor([[1., 2., 4.],
        [1., 2., 3.]])

In [23]:
# other ways
# arange
print("Arrange using : ", torch.arange(0,10)) # range it is and in the last we can provide the step (0,10,2)

# using linspace
print("Using LinSpace : ", torch.linspace(0,10,10))

# using the eye
print("Using eye : ", torch.eye(5))

# using the full 
print("Using full : ", torch.full((3,3),5))

Arrange using :  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using LinSpace :  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye :  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
