### numpy for math
also it is much faster than list broo
Numpy inplimentaion is in C lang

- NumPy (Numerical Python) is a Python library that is the core library for scientific
computing in Python.

- It contains a collection of tools and techniques that can be used to solve mathematical
models of problems in science and engineering

- One of these tools is a high-performance multidimensional array object that is a
powerful data structure for the efficient computation of arrays and matrices.

- To work with these arrays, there's a vast amount of high-level mathematical functions
operate on these matrices and arrays.

also numpy functions are 10x to 100x faster than custom functions

In [3]:
# insatll numpy
%pip install numpy

In [6]:
import numpy as np
np.__version__

'2.0.2'

Numpy 1d,2d and 3d array

In [12]:
#1D array
a1D = np.array([1,232,32,4])
print(a1D) 
print(type(a1D)) # this is for printing numpy type of array
help(np.array)

[  1 232  32   4]
<class 'numpy.ndarray'>
Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
  

In [15]:
# This is for printing length of array
# a1D.shape
# a1D.size
len(a1D)

4

In [22]:
# 2D array => list of list
arr = np.array([[12,31,12,32],
                [31,23,12,11]])
print("length of this array is : ",arr.shape)
print("array is here : ",arr)

length of this array is :  (2, 4)
array is here :  [[12 31 12 32]
 [31 23 12 11]]


In [33]:
# 3D array
a = np.array([
    [
        [1211,211],[1,21]
        ],
       [
           [73,232],[232,121]
           ]
           ])

print(a)
a.shape

[[[1211  211]
  [   1   21]]

 [[  73  232]
  [ 232  121]]]


(2, 2, 2)

## Data Types in numpy
- Numpy arrays(ndarray) are homogeneous, meaning all elements must be of the same data types


In [66]:
# np.array([1,2,3])
from numpy import float32
from numpy import bool

np.array([1,289,3,3.23],dtype=np.int32) # dtype means data type is given here int32 bit so yea if i wanna pass some floatign value it cant be possible so yea

np.array([1.2,12.1,2.0,121.82], dtype=float32)
# np.set_printoptions(formatter={'float_kind':'{:g}'.format})

np.array([1,True,False,True,21] ) # if i combined both true and false with numbers then it will convert the true false to 0,1 casue we mixed it up with int values
# also if we declare dtype= bool in the last so dtype gonna set here all bool also it will convers the int values to  Boolean

np.array([21,21,False,20,True,False],dtype= bool,) # here we have 20 so it counts the last digits so yea 
np.array(["Hello","jay","Niloy",21],dtype=str)

np.array([21,21,False,20,True,False],dtype= 'U1') # by using this we can kept only 1 value and trim other yayy

array(['2', '2', 'F', '2', 'T', 'F'], dtype='<U1')

### record array or structured array 
- Structured arrays in NumPy are homogeneous at the array level (each element has the same layout).
- We can specify a type and, optionally, a name on a per-column basis. This makes sorting and filtering even more powerful, and it can feel similar to working with data in
Excel, CSVs, or relational databases.


In [81]:
rec = [("Joy" , 20,32),
       ("Pial", 21,32),
       ("Bobby",32,11),
       ("Niloy",32,32)]

print(type(np.array(rec))) # by this we can convert any array or list to  numpy array 
# data = np.array(rec, dtype=[("name", "U15"),("age", "U15"),("marks", "U15")])
np.array(rec, dtype=[("name", "U15"),("age", "i4"),("marks", "i4")])
data = np.array(rec, dtype=[("name", "U15"),("age", "i4"),("marks", "i4")])

<class 'numpy.ndarray'>


array([('Joy', 20, 32), ('Pial', 21, 32), ('Bobby', 32, 11),
       ('Niloy', 32, 32)],
      dtype=[('name', '<U15'), ('age', '<i4'), ('marks', '<i4')])

### You can specify the dtype (data type) in several equivalent ways.

1. Using NumPy type strings (compact format) - [ ("name", "U15"), ("age", "14"), ("marks", "i4")]

2. Using NumPy type objects (recommended) - [("name", np.unicode_), ("age", ("age", ("marks", np. np.int32)]

3. Mixing Python built-in types and NumPy types - [("name", str), ("age", int), ("marks", np.int32)]

In [94]:
# rec[0]
# rec[1]
data["name"]
passed = data[data["marks"]>20]
print(passed)

[('Joy', 20, 32) ('Pial', 21, 32) ('Niloy', 32, 32)]


### By default, NumPy arrays (ndarray) are homogeneous, meaning all elements must be of the same data type.
- Homogeneous arrays allow:
    1. Vectorized operations
    2. Efficient memory layout (contiguous blocks)
    3. Fast computations using C under the hood
- NumPy is designed for arrays of fixed-size elements — typically numerical data type (integers, floats), but also supports strings, booleans, dates, and custom structured types

- All elements in a NumPy array share the same data type ( dtype ).
- The data is stored in a contiguous block of memory for efficiency.

It can support heterogeneous types using object arrays or structured types, but these lose most performance benefits.

In [95]:
het = np.array([5,True,'asd',2.2])
het

array(['5', 'True', 'asd', '2.2'], dtype='<U32')

In [96]:
het.dtype

dtype('<U32')

In [97]:
np.str_('5')

np.str_('5')

In [102]:
het = np.array([5,True,'asd',2.2], dtype= object) # if we use object then it will work nrmally
het

array([5, True, 'asd', 2.2], dtype=object)

In [101]:
type(het[2])

str

### ways to create Numpy Arrays


In [7]:
import numpy as np
# using list
np.array([1,2,3,1])
#  using tuple
np.array((1,2,3,43))


array([ 1,  2,  3, 43])

### Upcasting in Numpy
- it means u have to cast for example : float to int it called downCasting 
- also if we do int to float it called UpCasting 
- so in this case we always do UpCasting casuse in down casting there we lost so many data so
    experts prefered to do UpCasting always
    

In [15]:
np.array([1,2.2,23])

array([ 1. ,  2.2, 23. ])

In [ ]:
# 2D array
np.array([[1,2,3,4],[1,2,1,3]])

np.array([[[1,2.2,23]]], ndmin=5) # NOTE : by using ndmin we can define the minimum dimention of the array 
# the golden rule of ndmin  is : Final Dimensions = max(Your List's Actual Dimensions, ndmin)

np.array([1,2,3,4], dtype=complex) # it convert the all things into complex


array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

### data consisting of more than one data type


In [ ]:
x = np.array([(1,3),(2,12)], dtype=[('a','i4'),('b',np.float32)])
print(x)
print(x['a']) # by this this one prints the values of a
print(x['b']) # by this they prints the values of B we have stored ago

[(1,  3.) (2, 12.)]
[1 2]
[ 3. 12.]


### np.asarray

In [43]:
a = [1,2,3]
a = np.array([1,2,3])
np.asarray(a) is a  # its pointer address are same so its not a copy create also if it chnages in real one there will anothere diff address


True

### numpy.copy

In [44]:
a

array([1, 2, 3])

In [ ]:
np.array(a,copy=False) is a # if i change the copy to True then it will make a copy of that one (a) otherwise it wont it will just refers to the main One thats why their their addresses are same sooo yeapp
# b

True