### numpy for math
also it is much faster than list broo
Numpy inplimentaion is in C lang

- NumPy (Numerical Python) is a Python library that is the core library for scientific
computing in Python.

- It contains a collection of tools and techniques that can be used to solve mathematical
models of problems in science and engineering

- One of these tools is a high-performance multidimensional array object that is a
powerful data structure for the efficient computation of arrays and matrices.

- To work with these arrays, there's a vast amount of high-level mathematical functions
operate on these matrices and arrays.

also numpy functions are 10x to 100x faster than custom functions

In [1]:
# insatll numpy
%pip install numpy

In [4]:
import numpy as np
np.__version__

'2.4.4'

Numpy 1d,2d and 3d array

In [5]:
#1D array
a1D = np.array([1,232,32,4])
print(a1D) 
print(type(a1D)) # this is for printing numpy type of array
help(np.array)

[  1 232  32   4]
<class 'numpy.ndarray'>
Help on built-in function array in module numpy:

array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None
)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be

In [6]:
# This is for printing length of array
# a1D.shape
# a1D.size
len(a1D)

4

In [7]:
# 2D array => list of list
arr = np.array([[12,31,12,32],
                [31,23,12,11]])
print("length of this array is : ",arr.shape)
print("array is here : ",arr)

length of this array is :  (2, 4)
array is here :  [[12 31 12 32]
 [31 23 12 11]]


In [8]:
# 3D array
a = np.array([
    [
        [1211,211],[1,21]
        ],
       [
           [73,232],[232,121]
           ]
           ])

print(a)
a.shape

[[[1211  211]
  [   1   21]]

 [[  73  232]
  [ 232  121]]]


(2, 2, 2)

## Data Types in numpy
- Numpy arrays(ndarray) are homogeneous, meaning all elements must be of the same data types


In [36]:
# np.array([1,2,3])
from numpy import float32
from numpy import bool

np.array([1,289,3,3.23],dtype=np.int32) # dtype means data type is given here int32 bit so yea if i wanna pass some floatign value it cant be possible so yea

np.array([1.2,12.1,2.0,121.82], dtype=float32)
# np.set_printoptions(formatter={'float_kind':'{:g}'.format})

np.array([1,True,False,True,21] ) # if i combined both true and false with numbers then it will convert the true false to 0,1 casue we mixed it up with int values
# also if we declare dtype= bool in the last so dtype gonna set here all bool also it will convers the int values to  Boolean

np.array([21,21,False,20,True,False],dtype= bool,) # here we have 20 so it counts the last digits so yea 
np.array(["Hello","jay","Niloy",21],dtype=str)

np.array([21,21,False,20,True,False],dtype= 'U1') # by using this we can kept only 1 value and trim other yayy

array(['2', '2', 'F', '2', 'T', 'F'], dtype='<U1')

### record array or structured array 
- Structured arrays in NumPy are homogeneous at the array level (each element has the same layout).
- We can specify a type and, optionally, a name on a per-column basis. This makes sorting and filtering even more powerful, and it can feel similar to working with data in
Excel, CSVs, or relational databases.


In [37]:
rec = [("Joy" , 20,32),
       ("Pial", 21,32),
       ("Bobby",32,11),
       ("Niloy",32,32)]

print(type(np.array(rec))) # by this we can convert any array or list to  numpy array 
# data = np.array(rec, dtype=[("name", "U15"),("age", "U15"),("marks", "U15")])
np.array(rec, dtype=[("name", "U15"),("age", "i4"),("marks", "i4")])
data = np.array(rec, dtype=[("name", "U15"),("age", "i4"),("marks", "i4")])

<class 'numpy.ndarray'>


### You can specify the dtype (data type) in several equivalent ways.

1. Using NumPy type strings (compact format) - [ ("name", "U15"), ("age", "14"), ("marks", "i4")]

2. Using NumPy type objects (recommended) - [("name", np.unicode_), ("age", ("age", ("marks", np. np.int32)]

3. Mixing Python built-in types and NumPy types - [("name", str), ("age", int), ("marks", np.int32)]

In [38]:
# rec[0]
# rec[1]
data["name"]
passed = data[data["marks"]>20]
print(passed)

[('Joy', 20, 32) ('Pial', 21, 32) ('Niloy', 32, 32)]


### By default, NumPy arrays (ndarray) are homogeneous, meaning all elements must be of the same data type.
- Homogeneous arrays allow:
    1. Vectorized operations
    2. Efficient memory layout (contiguous blocks)
    3. Fast computations using C under the hood
- NumPy is designed for arrays of fixed-size elements — typically numerical data type (integers, floats), but also supports strings, booleans, dates, and custom structured types

- All elements in a NumPy array share the same data type ( dtype ).
- The data is stored in a contiguous block of memory for efficiency.

It can support heterogeneous types using object arrays or structured types, but these lose most performance benefits.

In [39]:
het = np.array([5,True,'asd',2.2])
het

array(['5', 'True', 'asd', '2.2'], dtype='<U32')

In [40]:
het.dtype

dtype('<U32')

In [41]:
np.str_('5')

np.str_('5')

In [42]:
het = np.array([5,True,'asd',2.2], dtype= object) # if we use object then it will work nrmally
het

array([5, True, 'asd', 2.2], dtype=object)

In [43]:
type(het[2])

str

### ways to create Numpy Arrays


In [44]:
import numpy as np
# using list
np.array([1,2,3,1])
#  using tuple
np.array((1,2,3,43))


array([ 1,  2,  3, 43])

### Upcasting in Numpy
- it means u have to cast for example : float to int it called downCasting 
- also if we do int to float it called UpCasting 
- so in this case we always do UpCasting casuse in down casting there we lost so many data so
    experts prefered to do UpCasting always
    

In [45]:
np.array([1,2.2,23])

array([ 1. ,  2.2, 23. ])

In [46]:
# 2D array
np.array([[1,2,3,4],[1,2,1,3]])

np.array([[[1,2.2,23]]], ndmin=5) # NOTE : by using ndmin we can define the minimum dimention of the array 
# the golden rule of ndmin  is : Final Dimensions = max(Your List's Actual Dimensions, ndmin)

np.array([1,2,3,4], dtype=complex) # it convert the all things into complex


array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

### data consisting of more than one data type


In [47]:
x = np.array([(1,3),(2,12)], dtype=[('a','i4'),('b',np.float32)])
print(x)
print(x['a']) # by this this one prints the values of a
print(x['b']) # by this they prints the values of B we have stored ago

[(1,  3.) (2, 12.)]
[1 2]
[ 3. 12.]


### np.asarray

In [48]:
a = [1,2,3]
a = np.array([1,2,3])
np.asarray(a) is a  # its pointer address are same so its not a copy create also if it chnages in real one there will anothere diff address


True

### numpy.copy

In [49]:
a

array([1, 2, 3])

In [50]:
np.array(a,copy=False) is a # if i change the copy to True then it will make a copy of that one (a) otherwise it wont it will just refers to the main One thats why their their addresses are same sooo yeapp
# b

True

### create an array X, with A reference Y and A copy Z

In [58]:
j = np.array([1,2,3,4])

In [59]:
p = j # it wont copy its reference will be same

In [60]:
sn = np.copy(j) # copy

### when we modify x,y changes, but not Z

In [61]:
j[0]=10

In [62]:
j

array([10,  2,  3,  4])

In [63]:
sn # its the copy of first one so it wont effect the sn value yea also it will be same as before we have saw

array([1, 2, 3, 4])

### Read and write data from a file
#### text files (.txt, .csv)

In [64]:
data = np.loadtxt("data.txt", delimiter=',')
print(data)

FileNotFoundError: data.txt not found.

In [ ]:
data = data ** 2 # here ** is power 
data

np.savetxt("output_data.txt", data, fmt='%f')

### Binary files (.npy and .npz)

In [65]:
arr = np.array([1,2,3,4])
np.save("arr.npy", arr)

In [66]:
arr = np.load("arr.npy")
print(arr)

[1 2 3 4]


In [67]:
# save multiple arrays
a1 = np.array([1,2,3,4])
a2 = np.array([2,3,4,2])
np.savez("ar.npz", arr1=a1, arr2=a2) # np.savez() as creating a digital Zip Folder.

In [68]:
# Load them back yayy
dataa = np.load("ar.npz")
print(dataa["arr1"]) # [1 2 3 4]
print(dataa["arr2"]) # [2 3 4 2]

[1 2 3 4]
[2 3 4 2]


### numpy.fromfunction

In [69]:
import numpy as np
np.fromfunction(lambda i,j : i==j, (5,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

### A new 1D array init from text data in a String

In [70]:
a= np.fromstring('1,2',dtype=int,sep=',')
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2])

### create a record array from a(flat) list of arrays

In [71]:
x1 = [1,2,3]
x2 = [2.0,2.0,6.0]
x3 = ['a','b','c']

In [72]:
a1 =list(zip(x1,x2,x3))
a2 = np.array(a1) # if someone create arr from plain data using this method this is called : Homogeneous array
a2 
# here size of a2 and r is totally diffrent and a2 side is massively bigger than r even through they hold the exact same value/ chars
# for example : 
# In r:
# we gave it strict blueprints: ('a','i4'), ('b','f4'), ('c','U1')
# Slot A (i4): takes 4 Bytes
# Slot B (f4): takes 4 Bytes
# Slot C (U1): takes 4 Bytes * Total RAM used for this row: 12 Bytes.
#  IN a2 : 
# slot a -> 16 bytes
#  slot B -> 16 bytes
#  slot c -> 16 bytes  # total is 48bytes

r = np.array(list(zip(x1,x2,x3)), dtype=[('a','i4'),('b','f4'),('c','U1')]) # and this one called Structured Record array
# r = np.array(list(zip(x1,x2,x3)), dtype=object) # and this one called Structured Record array
r # and here 'a','b', 'c' is the nickname or keys for the arrays 1,2,3


array([(1, 2., 'a'), (2, 2., 'b'), (3, 6., 'c')],
      dtype=[('a', '<i4'), ('b', '<f4'), ('c', '<U1')])

### Mathematics for NumPy
<img src="./math.png" width="1000">)

### Random Number Generaton
- np.random.rand() → Uniform distribution
- np. random. randn() → Normal distribntion


### Ex1: Select a random integer in your mind from [,10]
    - Every no. has equal probability of selection = 10

### Ex2: Roll a dice 1 times → Random value [1,6)
    - Roll one dice 10,000 times → and plot occurence of [1.6]

### Creating Numpy Arrays and Matrix using Built-in Functions

In [73]:
# arrange and linspace
import numpy as np
#range(start, stop, step)
# np.arrange(start, stop, step, dtype)

In [74]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [75]:
# np.arange(5,16,3)
np.arange(5,16,3, dtype=np.float32)

array([ 5.,  8., 11., 14.], dtype=float32)

In [76]:
np.arange(2,20,2.2)

array([ 2. ,  4.2,  6.4,  8.6, 10.8, 13. , 15.2, 17.4, 19.6])

In [77]:
# every 5th number from 50 in reverse order
np.arange(50,-1,-5)
# np.arange(50,-1,5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

### np.linspcae
```
np.linspcae(start, stop, num =50,endpoint=True, retstep=False, dtype=None, axis=0)
```

In [78]:
np.linspace(1,5,101) # 101-1 = 4/100 = 0.04

array([1.  , 1.04, 1.08, 1.12, 1.16, 1.2 , 1.24, 1.28, 1.32, 1.36, 1.4 ,
       1.44, 1.48, 1.52, 1.56, 1.6 , 1.64, 1.68, 1.72, 1.76, 1.8 , 1.84,
       1.88, 1.92, 1.96, 2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28,
       2.32, 2.36, 2.4 , 2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72,
       2.76, 2.8 , 2.84, 2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16,
       3.2 , 3.24, 3.28, 3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 ,
       3.64, 3.68, 3.72, 3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04,
       4.08, 4.12, 4.16, 4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48,
       4.52, 4.56, 4.6 , 4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92,
       4.96, 5.  ])

In [79]:
np.linspace(1,5,101, dtype=int) #at int data type here we actually lost data's 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5])

In [80]:
np.linspace(1,5,101, endpoint=True, retstep=False, dtype=None, axis=0)

# endpoint=True : 101 points = 100 gaps
# steps : 4/100 = 0.04 -> [1.00, 1.04, ...,5.00]

# endpoint=False : 101 points = 101 gaps
# Steps : 4/101 = $$\text{Step} = \frac{4}{101} = 0.03960396... -> [1.00,1.0396 ...4.960396]



array([1.  , 1.04, 1.08, 1.12, 1.16, 1.2 , 1.24, 1.28, 1.32, 1.36, 1.4 ,
       1.44, 1.48, 1.52, 1.56, 1.6 , 1.64, 1.68, 1.72, 1.76, 1.8 , 1.84,
       1.88, 1.92, 1.96, 2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28,
       2.32, 2.36, 2.4 , 2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72,
       2.76, 2.8 , 2.84, 2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16,
       3.2 , 3.24, 3.28, 3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 ,
       3.64, 3.68, 3.72, 3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04,
       4.08, 4.12, 4.16, 4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48,
       4.52, 4.56, 4.6 , 4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92,
       4.96, 5.  ])

### np.logspace()
```
np.logspace (start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```

In [81]:
# np.logspace(start, stop) # give. values evenly spaced in logarithmix space

np.logspace(1,2,5) # power(10,a) here a is 2 rn but its distance is diff bt their ratio is constant

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [82]:
np.linspace(1,100,num=5, dtype=int)

array([  1,  25,  50,  75, 100])

In [83]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so th

In [84]:
help(np.logspace)

Help on _ArrayFunctionDispatcher in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.

    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.25.0
        Non-scalar 'base` is now supported

    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boo

In [85]:
np.logspace(0,10, num=5, base=2, dtype=int) # [2^0, 2^10] -> power(2,10)

array([   1,    5,   32,  181, 1024])

In [86]:
# [0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1]

### Numpy array and matrix creation

In [87]:
# vector of zeros
np.zeros(6, dtype=int)

array([0, 0, 0, 0, 0, 0])

In [88]:
# matrix of zeros 
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [89]:
# vector of ones
np.ones(3, dtype=int)

array([1, 1, 1])

In [90]:
# matrix of ones
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [91]:
np.ones((3,3), dtype=int)*5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [92]:
np.empty((2,2)) # provides all garbage values

array([[9.9e-324, 1.5e-323],
       [2.0e-323, 9.9e-324]])

### np.reshape()
```
Diagonal,Triangular,Lower Triangular and upper Triangular Matrix
```

In [93]:
A = np.array([[1,2,3],
              [2,3,4],
              [3,4,6]])

In [94]:
# diagonal matrix
np.diag(np.diag(A)) # this is diagonal matrix

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 6]])

In [95]:
# lower tirnagular
np.tril(A)

array([[1, 0, 0],
       [2, 3, 0],
       [3, 4, 6]])

In [96]:
# upper tri
np.triu(A)

array([[1, 2, 3],
       [0, 3, 4],
       [0, 0, 6]])

In [97]:
A.shape

(3, 3)

### np.eye() (btw its an identify matrix)
```
np. pye (N, M=None, k=0, dtype=float, order= 'C')
````

In [98]:
np.eye(4, dtype=int) # at data type we can also add bool float anything.

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [99]:
mat1 = np.eye(5,4, dtype=int)
print(mat1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


### Accessing diagonals in NumPy
#### Use np.diag(A, k) where:
- k = o : main diagonal
- k > e : k-th diagonal above main diagonal
- k < e: k-th diagonal below main diagonal

In [100]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [101]:
xw = a.reshape((3,3))
xw

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
np.diag(xw, k=1)

array([1, 5])

In [103]:
np.diag(xw, k=0)

array([0, 4, 8])

In [104]:
np.diag(xw, k=-2)

array([6])

In [105]:
np.diag(xw, k=-1)

array([3, 7])

### Random number generation
1. Uniform Distribution: Occurence of value 1 to 6 if a die is rolled 10,000 times
2. Normal Distribution: Height of person in india for a sample of 1 Million People

In [106]:
# print random int matrix 
print(np.random.rand(2,3))
print(np.random.randn(2,3)) # Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal

[[0.45099863 0.59431989 0.18547578]
 [0.46504944 0.03385552 0.06477643]]
[[-1.73961967 -0.18792584  0.31437192]
 [-0.93221294  0.47720121 -1.69089708]]


In [107]:
print(np.random.randint(1,100,3)) # here i have start from 1 so 1 is strtign and end is 100 and we need 3 sample so yea

[42 43 42]


In [108]:
print(np.random.randint(1,100,(3,3))) # it will represent as matrix 


[[50 95 67]
 [68 62 71]
 [60 64 75]]


In [109]:
np.random.randint(1,7,20) # here we are gonna roll dice 20 times and range is 1 to n-1 so here we have 7 so here will be 7-1=6(1 to 6) range

array([3, 1, 1, 6, 4, 2, 1, 5, 4, 6, 6, 1, 1, 5, 3, 4, 4, 4, 4, 4])

### Dimension, Shape, Axis, Broadcasting and vectorization
```
Operations collapse the given axis, meaning elements along that axis are combined, and the axis disappears in the result.
```

In [3]:
# Axis = 0 means collapse first dimension
# axis=1 means collapse second dimension

# 2D array case
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6]])

In [5]:
np.sum(arr, axis=0) # sum along axis 0 (column wise)

array([5, 7, 9])

In [8]:
np.sum(arr, axis=1) #(Row-wise) 

array([ 6, 15])

In [12]:
# 3D array case
arr1 = np.array([[[1,2,3],
                 [4,5,6]],
                 
                 [[9,8,7],
                  [6,7,2]]])
arr1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 7, 2]]])

In [13]:
print(arr1.shape)

(2, 2, 3)


Shape (2, 2, 3) means:

- 2 blocks
- 2 rows per block
- 3 columns per row

In [14]:
np.sum(arr1, axis=0)

array([[10, 10, 10],
       [10, 12,  8]])

In [15]:
np.sum(arr1, axis=1).shape

(2, 3)

In [16]:
# Dimension -> How many axes?
# Shape -> Size along each axis
# Axis -> Direction along which operations are applied

### Broadcasting 

Broadcasting Rules
1. Compare shapes from the last dimension to the first.
    - If one shape has fewer dimensions, leading 1s are added automatically to the
      smaller shape.
2. Dimensions are compatible if:
    - They are equal, or
    - One of them is 1
3. Resulting shape is the maximum in each dimension after broadcasting.

In [17]:
# simple Example (1D + scalar)
arr01 = np.array([1,2,3])
print(arr01+5) # here broadcasts 5 to [6,7,8]

[6 7 8]


In [19]:
arr02 = np.array([[1,2,3],
                  [4,6,2]])
arr01 = np.array([1,2,3])
chu = arr02 + arr01
print(chu)


[[2 4 6]
 [5 8 5]]


In [20]:
# Broadcasting Fails When Shapes are Incompatible
pl = np.array([[1,2,4],
               [4,5,6]])
pl2 = np.array([[10,20],
               [40,50]])

In [24]:
pl3=(pl + pl2)
print(pl3) # here we can see that fails to broadcasting so yea in these types broadcasting fails


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

#### Broadcasting Internals Explained with Examples

1. Broadcasting in NumPy is implemented in C under the hood for speed.
2. Align shapes: (2,3) and (1,3)
3. Strides for B (row stride = O) → Reuse the same row twice
4. Compute element-wise sum in a new (2,3) array - using Vectorization

#### Advantages of Broadcasting
1. Memory efficient (no actual data replication).
2. Faster computations using vectorization instead of loops.

### 5. Vectorization

- Vectorization means performing operations on entire arrays at once instead of iterating
element by element in Python.
- NumPy operations are implemented in C, which avoids Python-level loops and
interpreter overhead.

In [25]:
xa = np.array([1,2,3])
xb = np.array([3,4,6])

In [26]:
xa + xb

array([4, 6, 9])

In [27]:
# if vectoraization doesnt exsists we should use loops which is gonna slower too much
[int(da+db) for da, db in zip(xa,xb)]

[4, 6, 9]

#### Indexing, Slicing and Subsetting in NumPy Arrays

In [2]:
# indexing
import numpy as np
arr11 = np.array([12,13,343,23])
print(arr11[0])

12


In [ ]:
# slicing 
arr12 = np.array([12,31,42,12,121])
print(arr12[1:4]) # it means it will start from index 1 and it will ends on 4-1 it means 3rd index
print(arr12[::4])


[31 42 12]
[ 12 121]


In [5]:
# subsetting 
print(arr12[arr12>25])

[ 31  42 121]


In [6]:
arr12 > 25

array([False,  True,  True, False,  True])

In [2]:
# Indexing, slicing and subsetting in Numpy
#indeixing - accesing indivisual elements ofa numpy array
import numpy as np
arr = np.array([10,121,11,21])
print(arr[2])

11


In [3]:
# slicing - we can access the range of elements also it creates a view not a copy
print(arr[1:4]) # [Start:: stop:step]

[121  11  21]


In [4]:
# Subsetting - 
arr = np.array([10,12,20,23,50])
print(arr[arr>32])

[50]


In [6]:
arr > 10

array([False,  True,  True,  True,  True])

In [8]:
from numpy.random import randint as ri
import numpy as np

In [9]:
A11 = ri(1,100,10)
A11

array([93, 77, 56, 65, 15,  7,  8, 91, 89, 61])

In [10]:
np.sort(A11)

array([ 7,  8, 15, 56, 61, 65, 77, 89, 91, 93])

In [13]:
M = ri(1,100,25).reshape(5,5)
M

array([[93, 83, 20, 66,  5],
       [95, 37, 41, 17, 64],
       [99, 57, 38, 14, 92],
       [54, 90, 91, 91, 52],
       [84, 22, 30, 57, 59]])

Axis=0 : row changes, column will be constant

Axis =1 : column changes, row will be constant

In [16]:
np.sort(M) # axis = 1

array([[ 5, 20, 66, 83, 93],
       [17, 37, 41, 64, 95],
       [14, 38, 57, 92, 99],
       [52, 54, 90, 91, 91],
       [22, 30, 57, 59, 84]])

In [19]:
np.sort(M, axis=1)

array([[ 5, 20, 66, 83, 93],
       [17, 37, 41, 64, 95],
       [14, 38, 57, 92, 99],
       [52, 54, 90, 91, 91],
       [22, 30, 57, 59, 84]])

In [22]:
np.max(M) # we can find max value 

np.int64(99)

In [23]:
M.max() # M -> instance of numpy array, M.max() => instance's mathod re call diche 

np.int64(99)

In [28]:
aray1 = np.arange(0,21,2)
print("New array : ",aray1)

New array :  [ 0  2  4  6  8 10 12 14 16 18 20]


In [29]:
aray1[[2,3,9]] # subsetting : creates a new array

array([ 4,  6, 18])

In [31]:
# matrix of random 2-digit numbers
mat = np.array(ri(12,100,15)).reshape(3,5)
mat

array([[87, 49, 25, 52, 45],
       [44, 76, 40, 72, 38],
       [93, 86, 54, 79, 49]])

In [34]:
# Subsetting
# matrix of random 2 digit numbers
mat1 = np.array(ri(10,100,15)).reshape(3,5)
mat1

array([[66, 14, 78, 72, 15],
       [41, 54, 17, 26, 92],
       [44, 27, 84, 41, 91]])

In [36]:
# elements grater than 50
mat1[mat1>50]

array([66, 78, 72, 54, 92, 84, 91])